version: "3.4"

networks:
  db_net:
    external: true
  default:

services:
  core: &service
    container_name: tender-hack-core
    environment:
      - RUN_LEVEL=dev
    entrypoint:
      - uvicorn
      - nebula.core:app
      - --host=0.0.0.0
      - --reload
    build:
      context: nebula
      dockerfile: docker/Dockerfile.server
      target: dev
    volumes:
      - ./nebula:/opt/app
    networks:
      - default
    restart: unless-stopped
    depends_on:
      - database
  database:
    container_name: tender-hack-postgres
    image: postgres:11
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: nebula
    networks:
      - db_net
      - default
    volumes:
      - ./.docker_data/postgres:/var/lib/postgresql/data
  nginx:
    build:
      context: nginx
    container_name: tender-hack-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - core
    networks:
      - default
