version: "3.4"

networks:
  db_net:
    external: true
  default:

services:
  core: &service
    container_name: tender-hack-core
    environment:
      - RUN_LEVEL=dev
    entrypoint:
      - uvicorn
      - services.core:app
      - --host=0.0.0.0
      - --reload
    build:
      context: nebula
      dockerfile: docker/Dockerfile.server
      target: dev
    volumes:
      - ./nebula:/opt/app
    networks:
      - default
    restart: unless-stopped
    depends_on:
      - database
  database:
    container_name: tender-hack-postgres
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: nebula
    networks:
      - db_net
      - default
    volumes:
      - ./.docker_data/mongo:/data/db
  nginx:
    build:
      context: nginx
    container_name: tender-hack-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - coredo
    networks:
      - default
